*) fix for last commit - an package-import was missing
*) bugfix for sub-documents containing no mime-type:
See: https://bugs.pxl.li/view.php?id=294
---
14 Dez 2008 03:25:45 INFO  org.paxle.indexer.impl.IndexerWorker  - Unable to index the sub-document 'Green Holiday Gift Ideas for Your Pet' of 'http://www.nowpublic.com/tag/Environment/feed?filter=news&order=popgs': Tried setting MimeType to null
java.lang.NullPointerException: Tried setting MimeType to null
        at org.paxle.core.doc.IndexerDocument.set(IndexerDocument.java:44)
        at org.paxle.indexer.impl.IndexerWorker.generateIIndexerDoc(IndexerWorker.java:248)
        at org.paxle.indexer.impl.IndexerWorker.execute(IndexerWorker.java:123)
        at org.paxle.indexer.impl.IndexerWorker.execute(IndexerWorker.java:36)
        at org.paxle.core.threading.AWorker.run(AWorker.java:148)
---

git-svn-id: svn://svn.paxle.net/paxle/trunk@1856 f5d3ab42-bacf-4b1a-9692-565be65a0cfe